language: haskell
addons:
  apt:
    packages:
      - libgnome-keyring-dev
ghc:
  - "7.0"
  - "7.2"
  - "7.4"
  - "7.6"
  - "7.8"
  - "7.10"
  - "8.0"
  - "8.2"
  - "8.4"
  - "8.6"
before_install:
  - cabal install alex
  - cabal install happy
  - cabal install c2hs
